### ISSUE TITLE
Error while using multilabel .

### ISSUE THREAD

**Issue by silverlining21** [runningJ/caffe_multi_label_code#1]
I got stuck in a error while using you python multi label data layer, I wonder do you have any ideal about that?  thank you in advance, following is my running log >>>

I0828 18:40:14.183374 25045 net.cpp:323] This network produces output accuracy_non_occ
I0828 18:40:14.183387 25045 net.cpp:323] This network produces output accuracy_occ_mouth
I0828 18:40:14.183399 25045 net.cpp:323] This network produces output accuracy_occ_right_eye
I0828 18:40:14.183410 25045 net.cpp:323] This network produces output accuracy_occ_two_eyes
I0828 18:40:14.183420 25045 net.cpp:323] This network produces output loss_non_occ
I0828 18:40:14.183431 25045 net.cpp:323] This network produces output loss_occ_mouth
I0828 18:40:14.183441 25045 net.cpp:323] This network produces output loss_occ_right_eye
I0828 18:40:14.183452 25045 net.cpp:323] This network produces output loss_occ_two_eyes
I0828 18:40:14.183595 25045 net.cpp:621] Collecting Learning Rate and Weight Decay.
I0828 18:40:14.183627 25045 net.cpp:338] Network initialization done.
I0828 18:40:14.184233 25045 solver.cpp:59] Solver scaffolding done.
...........batchloader class....
------------training start---------------
---------------BlobFetcher start------------------------
I0828 18:40:14.512773 25045 solver.cpp:258] Iteration 0, loss = 28.9413
I0828 18:40:14.512820 25045 solver.cpp:279]     Train net output #0: accuracy_non_occ = 0.4375
I0828 18:40:14.512830 25045 solver.cpp:279]     Train net output #1: accuracy_occ_mouth = 0.359375
I0828 18:40:14.512837 25045 solver.cpp:279]     Train net output #2: accuracy_occ_right_eye = 0.484375
I0828 18:40:14.512845 25045 solver.cpp:279]     Train net output #3: accuracy_occ_two_eyes = 0.3125
I0828 18:40:14.512856 25045 solver.cpp:279]     Train net output #4: loss_non_occ = 7.1785 (* 1 = 7.1785 loss)
I0828 18:40:14.512866 25045 solver.cpp:279]     Train net output #5: loss_occ_mouth = 8.51989 (* 1 = 8.51989 loss)
I0828 18:40:14.512877 25045 solver.cpp:279]     Train net output #6: loss_occ_right_eye = 5.27825 (* 1 = 5.27825 loss)
I0828 18:40:14.512887 25045 solver.cpp:279]     Train net output #7: loss_occ_two_eyes = 7.96462 (* 1 = 7.96462 loss)
I0828 18:40:14.512924 25045 solver.cpp:291]     lr = 0.0001, speed = 251.8ms/iter, throughput = 254.2sample/s
------------Iteration testing----------------
------------------calculate_accuracy---------------
Traceback (most recent call last):
  File "/home/root/caffe_multilabel/caffe_multi_label_code-master/datalayer.py", line 77, in forward
    blob=self.get_batch()#blob=[[image,[color,long,sleeve]],[image,[color,long,sleeve]],....[]]
  File "/home/root/caffe_multilabel/caffe_multi_label_code-master/datalayer.py", line 71, in get_batch
    return self.blob_queue.get()
AttributeError: 'multilabel' object has no attribute 'blob_queue'
Traceback (most recent call last):
  File "run_train.py", line 13, in <module>
    So.train_mode()
  File "/home/root/caffe_multilabel/caffe_multi_label_code-master/train.py", line 58, in train_mode
    self.calculate_accuracy()
  File "/home/root/caffe_multilabel/caffe_multi_label_code-master/train.py", line 68, in calculate_accuracy
    self.solver.test_nets[0].forward()
  File "/home/root/caffe-mn/python/caffe/pycaffe.py", line 95, in _Net_forward
    self._forward(start_ind, end_ind)
SystemError: NULL result without error in PyObject_Call
Terminating BlobFetcher
*** Aborted at 1503916845 (unix time) try "date -d @1503916845" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3eb000061d5) received by PID 25055 (TID 0x3fffa5826d30) from PID 25045; stack trace: ***
    @     0x3fffa57b04d8 ([vdso]+0x4d7)
    @     0x3efff6724568 (unknown)
    @     0x3fffa5763798 __new_sem_wait_slow.constprop.0
    @     0x3fff8ba33234 (unknown)
    @         0x10074de4 PyCFunction_Call
    @         0x1009cafc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x1009d358 PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x100be79c (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e60f0 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e5c0c (unknown)
    @         0x1007ef40 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x1009d0dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x1009da98 PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x100be79c (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e60f0 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e5c0c (unknown)
    @         0x1007ef40 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x1009d0dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx

**Comment by runningJ** [comment]
may be forget to self.set_queue(), i will resolve the problem as soon as possible.

**Comment by silverlining21** [comment]
I have tried add `self.set_queue()` at multilabel.setup()
![image](https://user-images.githubusercontent.com/8264748/29801329-9b26cfb6-8ca1-11e7-9564-106a61071639.png)


and I got the following erro log>>>

...........batchloader class....
------------training start---------------
---------------BlobFetcher start------------------------
I0829 10:16:51.629086 111502 solver.cpp:258] Iteration 0, loss = 25.6717
I0829 10:16:51.629135 111502 solver.cpp:279]     Train net output #0: accuracy_non_occ = 0.375
I0829 10:16:51.629150 111502 solver.cpp:279]     Train net output #1: accuracy_occ_mouth = 0.4375
I0829 10:16:51.629161 111502 solver.cpp:279]     Train net output #2: accuracy_occ_right_eye = 0.609375
I0829 10:16:51.629173 111502 solver.cpp:279]     Train net output #3: accuracy_occ_two_eyes = 0.546875
I0829 10:16:51.629186 111502 solver.cpp:279]     Train net output #4: loss_non_occ = 5.94874 (* 1 = 5.94874 loss)
I0829 10:16:51.629201 111502 solver.cpp:279]     Train net output #5: loss_occ_mouth = 7.18129 (* 1 = 7.18129 loss)
I0829 10:16:51.629218 111502 solver.cpp:279]     Train net output #6: loss_occ_right_eye = 7.50138 (* 1 = 7.50138 loss)
I0829 10:16:51.629230 111502 solver.cpp:279]     Train net output #7: loss_occ_two_eyes = 5.04025 (* 1 = 5.04025 loss)
I0829 10:16:51.629262 111502 solver.cpp:291]     lr = 0.0001, speed = 330.7ms/iter, throughput = 193.5sample/s
------------Iteration testing----------------
------------------calculate_accuracy---------------
Traceback (most recent call last):
  File "run_train.py", line 13, in <module>
    So.train_mode()
  File "/home/root/caffe_multilabel/caffe_multi_label_code-master/train.py", line 58, in train_mode
    self.calculate_accuracy()
  File "/home/root/caffe_multilabel/caffe_multi_label_code-master/train.py", line 70, in calculate_accuracy
    prob=self.solver.test_nets[0].blobs[ac_l].data.argmax(1)
ValueError: axis(=1) out of bounds
Terminating BlobFetcher
*** Aborted at 1503973034 (unix time) try "date -d @1503973034" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3eb0001b38e) received by PID 111510 (TID 0x3fff8cac6d30) from PID 111502; stack trace: ***
    @     0x3fff8ca504d8 ([vdso]+0x4d7)
    @       0x7200000039 (unknown)
    @     0x3fff7e51ce00 (unknown)
    @     0x3fff7e52a9ac (unknown)
    @     0x3fff7e51b070 jpeg_read_scanlines
    @     0x3fff74d843d8 ImagingJpegDecode
    @     0x3fff74d68050 (unknown)
    @         0x10074dac PyCFunction_Call
    @         0x1009cafc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x1009d358 PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x100be79c (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e60f0 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100837c4 PyObject_CallFunctionObjArgs
    @         0x101d6580 (unknown)
    @         0x101a2e50 (unknown)
    @     0x3fff8c074b9c PyArray_GetAttrString_SuppressException
    @     0x3fff8c0828f8 PyArray_FromInterface
    @     0x3fff8c0834f0 PyArray_GetArrayParamsFromObject
    @     0x3fff8c083a68 PyArray_FromAny
    @     0x3fff8c083ff0 PyArray_CheckFromAny
    @     0x3fff8c12d6a4 _array_fromobject
    @         0x10074de4 PyCFunction_Call
    @         0x1009e148 PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x100bea24 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x1009f17c PyEval_EvalFrameEx
Terminating BlobFetcher
*** Aborted at 1503973034 (unix time) try "date -d @1503973034" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3eb0001b38e) received by PID 111508 (TID 0x3fff8cac6d30) from PID 111502; stack trace: ***
    @     0x3fff8ca504d8 ([vdso]+0x4d7)
    @     0x3fff71cf4630 (unknown)
    @     0x3fff8c031ab8 array_free
    @     0x3fff8c032248 array_dealloc
    @         0x1009d388 PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x1009d358 PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x100be79c (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e60f0 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e5c0c (unknown)
    @         0x1007ef40 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x1009d0dc PyEval_EvalFrameEx
    @         0x1009d1dc PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x1009da98 PyEval_EvalFrameEx
    @         0x10093ba8 PyEval_EvalCodeEx
    @         0x100be79c (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100e60f0 (unknown)
    @         0x10074bd4 PyObject_Call
    @         0x100a3ea8 PyEval_CallObjectWithKeywords
    @         0x1004939c PyEval_CallFunction
Terminating BlobFetcher

**Comment by runningJ** [comment]
may be you should check your accuray_layers  at params.py

**Comment by silverlining21** [comment]
I just keep the acc layer name in the train.pt the same with the dict `accuracy_layers_dic` in `params.py`,  shoudn't I consider the order of the different acc layer in the dict or other place, right ? 

![image](https://user-images.githubusercontent.com/8264748/29806915-3c48f28a-8cc4-11e7-876d-bb5bc690fd68.png)

**Comment by runningJ** [comment]
you can use pdb debug  code. i think the problem is that can not get layer output.

**Comment by silverlining21** [comment]
thanks for your advice. after I use gbd debug the code, I found that in the `TEST` phase the output shape of accuracy layer is abnormal. I have check the 

> ------------Iteration testing----------------
------------------calculate_accuracy---------------
> /home/root/caffe_multilabel/caffe_multi_label_code-master/train.py(68)calculate_accuracy()
-> for i in range(self.solver_param.test_iter[0]):
(Pdb) b 71
Breakpoint 1 at /home/root/caffe_multilabel/caffe_multi_label_code-master/train.py:71
(Pdb) l
 63  	        print "------------------calculate_accuracy---------------"
 64  	        accuracy_nums=len(pa.accuracy_layers_dic)
 65  	        input_labels=pa.top_names[1:]
 66  	        correct=np.zeros(accuracy_nums)
 67  	        pdb.set_trace()
 68  ->	        for i in range(self.solver_param.test_iter[0]):
 69  	            self.solver.test_nets[0].forward()
 70  	            for j,ac_l,inp_l in zip(range(accuracy_nums),pa.accuracy_layers_dic,input_labels):
 71 B	                prob=self.solver.test_nets[0].blobs[ac_l].data.argmax(1)
 72  	                gt=np.squeeze(self.solver.test_nets[0].blobs[inp_l].data)
 73  	                correct[j]+=np.sum(prob==gt)
(Pdb) c
> /home/root/caffe_multilabel/caffe_multi_label_code-master/train.py(71)calculate_accuracy()
-> prob=self.solver.test_nets[0].blobs[ac_l].data.argmax(1)
(Pdb) l
 66  	        correct=np.zeros(accuracy_nums)
 67  	        pdb.set_trace()
 68  	        for i in range(self.solver_param.test_iter[0]):
 69  	            self.solver.test_nets[0].forward()
 70  	            for j,ac_l,inp_l in zip(range(accuracy_nums),pa.accuracy_layers_dic,input_labels):
 71 B->	                prob=self.solver.test_nets[0].blobs[ac_l].data.argmax(1)
 72  	                gt=np.squeeze(self.solver.test_nets[0].blobs[inp_l].data)
 73  	                correct[j]+=np.sum(prob==gt)
 74  	
 75  	        for i in range(accuracy_nums):
 76  	            out=correct[i]/(pa.batchsize_dic['val']*self.solver_param.test_iter[0])
(Pdb) self.solver.test_nets[0].blobs[ac_l].data
array(0.984375, dtype=float32)
(Pdb) self.solver.test_nets[0].blobs[ac_l].data.shape
()
(Pdb) self.solver.test_nets[0].blobs[inp_l].data.shape
(64, 1)
(Pdb) 

Here is setting of my params.py>>>
`import numpy as np

class Params(object):
    def __init__(self):
        self.caffe_root='/home/root/caffe-NOMPI/python'
        self.batchsize_dic={'train':64,'val':64}
        self.channel=1
        self.height=128
        self.width=128
        self.GPU=True
        self.data_label_dic={'train':['/home/root/data/occ_data',
                                     'train.txt'],
                             'val':['/home/root/data/occ_data',
                                   'val.txt']}
        self.top_names=['data','non_occ','occ_mouth','occ_right_eye','occ_two_eyes']
        self.mean=np.float32([128.0,128.0,128.0])
        self.solver='./prototxt/solver.pt'
        self.pretrain='/home/root/project/msra/models/shuffle_iter_1680000.caffemodel'
        self.device=0
        self.output_dir='/home/root/caffe_multilabel/caffe_multi_label_code-master'
        self.accuracy_layers_dic=['accuracy_non_occ','accuracy_occ_mouth','accuracy_occ_right_eye','accuracy_occ_two_eyes']
#---------------------------------------------------------------------------
        self.Using_Process_dic={'train':True,'val':True}
        self.queue_num=10
`
